version: 2
jobs:

  build:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Download packer
          command: |
            wget -q https://releases.hashicorp.com/packer/1.5.6/packer_1.5.6_linux_amd64.zip
            unzip packer*.zip  
            chmod +x packer
      - run:
          name: Validate Packer Template
          command: ./packer validate ami.json
      - run:
          name: Build AMI
          command: |
            ./packer build \
            ami.json